var nwe = new Player('Wolf',red,0)

new Settlement(nwe,444).render()




// new Port(new HexPoint( 0.5, 8),sheep,"2:1").render()
// // new Port(new HexPoint( 1.5, 8),'#cccccc', 2).render()
// // new Port(new HexPoint( 2.5, 8),'#cccccc', 3).render()
// // new Port(new HexPoint( 3.5, 6),'#cccccc', 4).render()
// new Port(new HexPoint( 3.5, 5),multi,"3:1").render()
// // new Port(new HexPoint( 4.5, 3),'#cccccc', 6).render()
// // new Port(new HexPoint( 4.5, 2),'#cccccc', 7).render()
// new Port(new HexPoint( 5.5, 0),multi,"3:1").render()
// // new Port(new HexPoint( 4.5,-2),'#cccccc', 9).render()
// // new Port(new HexPoint( 4.5,-3),'#cccccc',10).render()
// new Port(new HexPoint( 3.5,-5),brick,"2:1").render()
// // new Port(new HexPoint( 3.5,-6),'#cccccc',12).render()
// // new Port(new HexPoint( 2.5,-8),'#cccccc',13).render()
// // new Port(new HexPoint( 1.5,-8),'#cccccc',14).render()
// new Port(new HexPoint( 0.5,-8),woods,"2:1").render()
// // new Port(new HexPoint(-0.5,-8),'#cccccc',16).render()
// // new Port(new HexPoint(-1.5,-8),'#cccccc',17).render()
// new Port(new HexPoint(-2.5,-8),multi,"3:1").render()
// // new Port(new HexPoint(-3.5,-6),'#cccccc',19).render()
// // new Port(new HexPoint(-3.5,-5),'#cccccc',20).render()
// new Port(new HexPoint(-4.5,-3),grain,"2:1").render()
// // new Port(new HexPoint(-4.5,-2),'#cccccc',22).render()
// // new Port(new HexPoint(-5.5, 0),'#cccccc',23).render()
// // new Port(new HexPoint(-4.5, 2),'#cccccc',24).render()
// new Port(new HexPoint(-4.5, 3),stone,"2:1").render()
// // new Port(new HexPoint(-3.5, 5),'#cccccc',26).render()
// // new Port(new HexPoint(-3.5, 6),'#cccccc',27).render()
// new Port(new HexPoint(-2.5, 8),multi,"3:1").render()
// // new Port(new HexPoint(-1.5, 8),'#cccccc',29).render()
// // new Port(new HexPoint(-0.5, 8),'#cccccc',30).render()