var nwe = new Player('Wolf',red,0)
var amu = new Player('Anna',blue,1)
var aru = new Player('Amy' ,white,2)
var ltu = new Player('Luke',orange,3)

new Settlement(nwe,334).render()
new Road(nwe,241).render()
new Settlement(amu,624).render()
new Road(amu,623).render()
new Settlement(aru,232).render()
new Road(aru,233).render()
new Settlement(ltu,254).render()
new Road(ltu,253).render()

new Settlement(ltu,352).render()
new Road(ltu,351).render()
new Settlement(aru,534).render()
new Road(aru,533).render()
new Settlement(amu,514).render()
new Road(amu,421).render()
new Settlement(nwe,434).render()
new Road(nwe,341).render()
